# Generated by Django 4.2.14 on 2024-07-19 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=125, verbose_name='Story Title')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Index')),
                ('title', models.CharField(max_length=125, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('img', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('bg_color', models.CharField(max_length=7, verbose_name='Background Color')),
                ('text_color', models.CharField(max_length=7, verbose_name='Text Color')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='stories.story', verbose_name='Story')),
            ],
            options={
                'verbose_name': 'Frame',
                'verbose_name_plural': 'Frames',
                'unique_together': {('story', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.CharField(max_length=255, verbose_name='Button Text')),
                ('link_index', models.PositiveSmallIntegerField(verbose_name='Link Index')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='stories.frame', verbose_name='Frame')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
            },
        ),
    ]
