# Generated by Django 4.2.14 on 2024-07-19 20:40

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='text_color',
        ),
        migrations.AddField(
            model_name='frame',
            name='color_details',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
