# Generated by Django 4.2.14 on 2024-07-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_frame_bg_color_remove_frame_text_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='color_details',
            new_name='colors',
        ),
    ]
